src/main/java/py/com/controlgym/entities/Usuarios.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package py.com.controlgym.entities;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
import org.codehaus.jackson.annotate.JsonIgnore;

/**
 *
 * @author broja
 */
@Entity
@Table(name = "usuarios", catalog = "gym_control", schema = "public")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Usuarios.findAll", query = "SELECT u FROM Usuarios u"),
    @NamedQuery(name = "Usuarios.findByUsuario", query = "SELECT u FROM Usuarios u WHERE u.nombreUsuario = :nombreUsuario and u.estado = 1"),
    @NamedQuery(name = "Usuarios.findByIdUsuario", query = "SELECT u FROM Usuarios u WHERE u.idUsuario = :idUsuario"),
    @NamedQuery(name = "Usuarios.findByNombreUsuario", query = "SELECT u FROM Usuarios u WHERE u.nombreUsuario = :nombreUsuario"),
    @NamedQuery(name = "Usuarios.findByPasswd", query = "SELECT u FROM Usuarios u WHERE u.passwd = :passwd"),
    @NamedQuery(name = "Usuarios.findByEstado", query = "SELECT u FROM Usuarios u WHERE u.estado = :estado"),
    @NamedQuery(name = "Usuarios.findByFechaAcceso", query = "SELECT u FROM Usuarios u WHERE u.fechaAcceso = :fechaAcceso"),
    @NamedQuery(name = "Usuarios.findByNombre", query = "SELECT u FROM Usuarios u WHERE u.nombre = :nombre"),
    @NamedQuery(name = "Usuarios.findByNivel", query = "SELECT u FROM Usuarios u WHERE u.nivel = :nivel")})
public class Usuarios implements Serializable {
    @OneToMany(mappedBy = "usrIns")
    private List<VentaDet> ventaDetList;
    @OneToMany(mappedBy = "idUsuario")
    private List<Ventas> ventasList;
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id_usuario")
    private Integer idUsuario;
    @Size(max = 100)
    @Column(name = "nombre_usuario")
    private String nombreUsuario;
    @Size(max = 100)
    @Column(name = "passwd")
    private String passwd;
    @Column(name = "estado")
    private Integer estado;
    @Column(name = "fecha_acceso")
    @Temporal(TemporalType.TIMESTAMP)
    private Date fechaAcceso;
    @Size(max = 50)
    @Column(name = "nombre")
    private String nombre;
    @Column(name = "nivel")
    private Integer nivel;
    @JoinColumn(name = "id_gimnasio", referencedColumnName = "id_gimnasio")
    @ManyToOne
    private Gimnasios idGimnasio;

    public Usuarios() {
    }

    public Usuarios(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    public Integer getIdUsuario() {
        return idUsuario;
    }

    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }

    public String getNombreUsuario() {
        return nombreUsuario;
    }

    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    public String getPasswd() {
        return passwd;
    }

    public void setPasswd(String passwd) {
        this.passwd = passwd;
    }

    public Integer getEstado() {
        return estado;
    }

    public void setEstado(Integer estado) {
        this.estado = estado;
    }

    public Date getFechaAcceso() {
        return fechaAcceso;
    }

    public void setFechaAcceso(Date fechaAcceso) {
        this.fechaAcceso = fechaAcceso;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Integer getNivel() {
        return nivel;
    }

    public void setNivel(Integer nivel) {
        this.nivel = nivel;
    }

    public Gimnasios getIdGimnasio() {
        return idGimnasio;
    }

    public void setIdGimnasio(Gimnasios idGimnasio) {
        this.idGimnasio = idGimnasio;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idUsuario != null ? idUsuario.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Usuarios)) {
            return false;
        }
        Usuarios other = (Usuarios) object;
        if ((this.idUsuario == null && other.idUsuario != null) || (this.idUsuario != null && !this.idUsuario.equals(other.idUsuario))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "py.com.controlgym.entities.Usuarios[ idUsuario=" + idUsuario + " ]";
    }

    @XmlTransient
    @JsonIgnore
    public List<VentaDet> getVentaDetList() {
        return ventaDetList;
    }

    public void setVentaDetList(List<VentaDet> ventaDetList) {
        this.ventaDetList = ventaDetList;
    }

    @XmlTransient
    @JsonIgnore
    public List<Ventas> getVentasList() {
        return ventasList;
    }

    public void setVentasList(List<Ventas> ventasList) {
        this.ventasList = ventasList;
    }
    
}

src/main/java/py/com/controlgym/controller/UsuariosController.java
package py.com.controlgym.controller;

import py.com.controlgym.entities.Usuarios;
import java.io.Serializable;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.event.ActionEvent;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import py.com.controlgym.controller.login.LoginBean;
import py.com.controlgym.controller.util.HashTextTest;
import py.com.controlgym.facade.UsuariosFacade;

@Named(value = "usuariosController")
@ViewScoped
public class UsuariosController extends AbstractController<Usuarios> implements Serializable {

    @EJB
    private UsuariosFacade ejbFacade;
    private boolean activo;

    public boolean isActivo() {
        return activo;
    }

    public void setActivo(boolean activo) {
        this.activo = activo;
    }

    public UsuariosController() {
        super(Usuarios.class);
    }

    public String evalEstado(String valor) {
        int valorNum = Integer.parseInt(valor);
        String estado;
        if (valorNum == 1) {
            estado = "Activo";
        } else {
            estado = "Inactivo";
        }
        return estado;
    }

    public String evalNivel(String valor) {
        int valorNum = Integer.parseInt(valor);
        String nivel;
        switch (valorNum) {
            case 1:
                nivel = "Administrador";
                break;
            case 2:
                nivel = "Propietario";
                break;
            default:
                nivel = "Encargado";
                break;
        }
        return nivel;
    }

    @Override
    public void saveNew(ActionEvent event) {
        super.getSelected().setEstado(1);
        super.getSelected().setPasswd(HashTextTest.sha1(super.getSelected().getPasswd()));
        super.saveNew(event);
    }

    @Override
    public void save(ActionEvent event) {
        if (activo) {
            super.getSelected().setEstado(1);
        } else {
            super.getSelected().setEstado(0);
        }
        super.save(event);
    }

    public void prepareEdit(ActionEvent event) {
        activo = this.getSelected().getEstado() == 1;
    }
    private String newPass1;
    private String newPass2;
    private String oldPass;

    public String getNewPass1() {
        return newPass1;
    }

    public void setNewPass1(String newPass1) {
        this.newPass1 = newPass1;
    }

    public String getNewPass2() {
        return newPass2;
    }

    public void setNewPass2(String newPass2) {
        this.newPass2 = newPass2;
    }

    public String getOldPass() {
        return oldPass;
    }

    public void setOldPass(String oldPass) {
        this.oldPass = oldPass;
    }

    public void updatePass(ActionEvent event) {
        FacesMessage message;
        FacesContext context = FacesContext.getCurrentInstance();
        if (newPass1.matches(newPass2)) {
            //recuperar usuario
            LoginBean lb = new LoginBean();
            Usuarios u = ejbFacade.find(lb.getUsuario());
            //comparar contraseña actual
            if (u.getPasswd().matches(HashTextTest.sha1(oldPass))) {
                u.setPasswd(HashTextTest.sha1(newPass1));
                //actualizar bd
                int i = ejbFacade.updatePass(u);
                System.out.println(i);
                if (i == 1) {
                    message = new FacesMessage(FacesMessage.SEVERITY_INFO, "Éxito", "Actualización realizada con éxito");
                    context.addMessage(null, message);

                } else {
                    message = new FacesMessage(FacesMessage.SEVERITY_FATAL, "Error", "No se pudo actualizar en la Base de Datos");
                    context.addMessage(null, message);

                }

                //RequestContext.getCurrentInstance().showMessageInDialog(message);
            } else {
                message = new FacesMessage(FacesMessage.SEVERITY_FATAL, "Error", "Las contraseña anterior no coincide. Intente de nuevo");
                context.addMessage(null, message);
                //RequestContext.getCurrentInstance().showMessageInDialog(message);
            }
        } else {
            message = new FacesMessage(FacesMessage.SEVERITY_FATAL, "Error", "Las contraseñas no coinciden. Intente de nuevo");
            context.addMessage(null, message);
            //RequestContext.getCurrentInstance().showMessageInDialog(message);
        }
    }
}

src/main/java/py/com/controlgym/controller/VentasController.java
package py.com.controlgym.controller;

import py.com.controlgym.entities.Ventas;
import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Collection;
import java.util.Date;
import javax.ejb.EJB;
import javax.faces.event.ActionEvent;
import javax.inject.Named;
import javax.faces.view.ViewScoped;
import py.com.controlgym.controller.login.LoginBean;
import py.com.controlgym.entities.Estudiantes;
import py.com.controlgym.entities.Gimnasios;
import py.com.controlgym.entities.Producto;
import py.com.controlgym.entities.VentaDet;
import py.com.controlgym.facade.EstudiantesFacade;
import py.com.controlgym.facade.GimnasiosFacade;
import py.com.controlgym.facade.ProductoFacade;
import py.com.controlgym.facade.VentasFacade;
import py.com.controlgym.facade.UsuariosFacade;

@Named(value = "ventasController")
@ViewScoped
public class VentasController extends AbstractController<Ventas> implements Serializable {

    @EJB
    private GimnasiosFacade gimnasiosFacade;

    @EJB
    private EstudiantesFacade estudiantesFacade;

    @EJB
    private UsuariosFacade usuariosFacade;

    @EJB
    private VentasFacade ventasFacade;

    @EJB
    private ProductoFacade productoFacade;
    private boolean requiereCantidad=true;
    private VentaDet detalle;
    private Producto producto;
    private final LoginBean loginBean = new LoginBean();

    public VentasController() {
        super(Ventas.class);
    }

    public VentaDet getDetalle() {
        return detalle;
    }

    public void setDetalle(VentaDet detalle) {
        this.detalle = detalle;
    }

    @Override
    public Collection<Ventas> getItems() {
        if (loginBean.tieneRol()) {
            return super.getItems();
        } else {
            Integer idGimnasio = loginBean.getIdGimnasio();
            return ventasFacade.findAll(idGimnasio);
        }
    }
    private Ventas venta;

    @Override
    public Ventas prepareCreate(ActionEvent event) {
        venta = super.prepareCreate(event);
        venta.setIdGimnasio(LoadGimnasio());
        venta.setEstado(1);
        venta.setFechaEmision(new Date());
        venta.setIdUsuario(usuariosFacade.find(loginBean.getUsuario()));
        venta.setVentaDetList(new ArrayList<VentaDet>());
        return venta;
    }

    @Override
    public void saveNew(ActionEvent event) {
        super.saveNew(event);
        for (VentaDet det : venta.getVentaDetList()) {
            int tipo = det.getIdProducto().getTipoProducto();
            switch (tipo) {
                //Actualizar Stock de Productos
                case 1:
                    Producto p = det.getIdProducto();
                    p.setCantidad(p.getCantidad() - det.getCantidad());
                    //Aca validar minimo y alertar
                    productoFacade.edit(p);
                    break;
                // Actualizar Cuotas // CASE 4 Siguiente vuelta
                case 2:
                case 3:
                case 6:
                    Calendar cal = Calendar.getInstance();
                    cal.add(Calendar.MONTH, 1);
                    Estudiantes e = super.getSelected().getIdEstudiante();
                    e.setFechaProximoPago(cal.getTime());
                    estudiantesFacade.edit(e);
                    break;
                case 5:// Promo 3x2
                    cal = Calendar.getInstance();
                    cal.add(Calendar.MONTH, 3);
                    e = super.getSelected().getIdEstudiante();
                    e.setFechaProximoPago(cal.getTime());
                    estudiantesFacade.edit(e);
                    break;
            }
        }
    }
    public Producto getProducto() {
        return producto;
    }

    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public String evalEstado(String valor) {
        int valorNum = Integer.parseInt(valor);
        String estado;
        if (valorNum == 1) {
            estado = "Activo";
        } else {
            estado = "Anulado";
        }
        return estado;
    }

    public void onProductoSelect() {
        requiereCantidad=true;
        detalle = new VentaDet();
        detalle.setIdProducto(producto);
        if(producto.getTipoProducto()==1){
            requiereCantidad=false;
        }else{
            detalle.setCantidad(1);
        }
    }

    public boolean isRequiereCantidad() {
        return requiereCantidad;
    }

    public void setRequiereCantidad(boolean requiereCantidad) {
        this.requiereCantidad = requiereCantidad;
    }
    public void addItemDetalles() {
        detalle.setIdVenta(this.getSelected());
        BigInteger cantidad = BigInteger.ONE;
        if (detalle.getIdProducto().getTipoProducto() == 1) {
            cantidad = new BigInteger(detalle.getCantidad().toString());
        }
        BigInteger importeActual = super.getSelected().getTotal()==null? BigInteger.ZERO:super.getSelected().getTotal();
        cantidad=cantidad.multiply(detalle.getIdProducto().getPrecioUnitario());
        importeActual=importeActual.add(cantidad);
        detalle.setValorVenta(cantidad);
        super.getSelected().getVentaDetList().add(detalle);
        super.getSelected().setTotal(importeActual);                       
    }

    public void removeItemDetalles(VentaDet item) {
        this.getSelected().setTotal(
                this.getSelected().getTotal().subtract(item.getValorVenta()));
        this.getSelected().getVentaDetList().remove(item);
    }

    private Gimnasios LoadGimnasio() {
        Integer idGimnasio = loginBean.getIdGimnasio();
        Gimnasios g = gimnasiosFacade.find(idGimnasio);
        return g;
    }
}

src/main/webapp/app/usuarios/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="UsuariosCreateDlg" widgetVar="UsuariosCreateDialog" styleClass="modalResponsivo" modal="true" resizable="false" appendTo="@(body)" header="#{myBundle.CreateUsuariosTitle}" closeOnEscape="true">

            <h:form id="UsuariosCreateForm">

                <h:panelGroup id="display">
                    <p:panelGrid columns="2" columnClasses="column,sui-g-12 ui-md-2,ui-g-12 ui-md-10" layout="grid">

                        <p:outputLabel value="#{myBundle.CreateUsuariosLabel_nombre}" for="nombre" />
                        <p:inputText id="nombre" value="#{usuariosController.selected.nombre}" title="#{myBundle.CreateUsuariosTitle_nombre}"/>

                        <p:outputLabel value="#{myBundle.CreateUsuariosLabel_nombreUsuario}" for="nombreUsuario" />
                        <p:inputText id="nombreUsuario" value="#{usuariosController.selected.nombreUsuario}" title="#{myBundle.CreateUsuariosTitle_nombreUsuario}"/>

                        <p:outputLabel value="#{myBundle.CreateUsuariosLabel_passwd}" for="passwd" />
                        <p:password id="passwd" value="#{usuariosController.selected.passwd}" title="#{myBundle.CreateUsuariosTitle_passwd}"/>

                        <p:outputLabel value="Gimnasio" for="idGimnasio" />
                        <p:selectOneMenu id="idGimnasio" value="#{usuariosController.selected.idGimnasio}" required="true" requiredMessage="#{myBundle.CreateUsuariosRequiredMessage_idGimnasio}" converter="gimnasiosConverter">
                            <f:selectItem itemLabel="#{myBundle.SelectOneMessage}"/>
                            <f:selectItems value="#{gimnasiosController.items}"
                                           var="idGimnasioItem"
                                           itemValue="#{idGimnasioItem}"
                                           itemLabel="#{idGimnasioItem.razonSocial}"
                                           />
                        </p:selectOneMenu>

                        <p:outputLabel value="#{myBundle.CreateUsuariosLabel_nivel}" for="nivel" />
                        <p:selectOneMenu id="nivel" value="#{usuariosController.selected.nivel}" required="true">
                            <f:selectItem itemLabel="Seleccione Uno" itemValue="" />
                            <f:selectItem itemLabel="Administrador" itemValue="1" />
                            <f:selectItem itemLabel="Propietario" itemValue="2" />
                            <f:selectItem itemLabel="Encargado" itemValue="3" />                            
                        </p:selectOneMenu>

                    </p:panelGrid>
                    <p:commandButton actionListener="#{usuariosController.saveNew}" value="#{myBundle.Save}" update="display,:UsuariosListForm:datalist,:growl" oncomplete="handleSubmit(xhr,status,args,PF('UsuariosCreateDialog'));">
                        <p:confirm header="#{myBundle.ConfirmationHeader}" message="#{myBundle.ConfirmCreateMessage}" icon="ui-icon-alert"/>
                    </p:commandButton>

                    <p:commandButton value="#{myBundle.Cancel}" oncomplete="PF('UsuariosCreateDialog').hide()" update="display" process="@this" immediate="true" resetValues="true"/>
                </h:panelGroup>

            </h:form>

        </p:dialog>

    </ui:composition>

</html>

src/main/webapp/app/usuarios/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>
        <p:dialog id="UsuariosEditDlg" widgetVar="UsuariosEditDialog" styleClass="modalResponsivo" modal="true" resizable="false"  appendTo="@(body)" header="#{myBundle.EditUsuariosTitle}" closeOnEscape="true">

            <h:form id="UsuariosEditForm">

                <h:panelGroup id="display">
                    <p:panelGrid  columns="2" columnClasses="column,sui-g-12 ui-md-2,ui-g-12 ui-md-10" layout="grid" rendered="#{usuariosController.selected != null}">

                        <p:outputLabel value="#{myBundle.EditUsuariosLabel_nombreUsuario}" for="nombreUsuario" />
                        <p:inputText id="nombreUsuario" value="#{usuariosController.selected.nombreUsuario}" title="#{myBundle.EditUsuariosTitle_nombreUsuario}"/>

                        <p:outputLabel value="Activo" for="estado" />
                         <p:selectBooleanCheckbox id="estado" value="#{usuariosController.activo}" title="#{myBundle.EditUsuariosTitle_estado}"/>

                        <p:outputLabel value="#{myBundle.EditUsuariosLabel_nombre}" for="nombre" />
                        <p:inputText id="nombre" value="#{usuariosController.selected.nombre}" title="#{myBundle.EditUsuariosTitle_nombre}"/>

                        <p:outputLabel value="Gimnasio" for="idGimnasio" />
                        <p:selectOneMenu id="idGimnasio" value="#{usuariosController.selected.idGimnasio}" required="true" requiredMessage="#{myBundle.CreateUsuariosRequiredMessage_idGimnasio}" converter="gimnasiosConverter">
                            <f:selectItem itemLabel="#{myBundle.SelectOneMessage}"/>
                            <f:selectItems value="#{gimnasiosController.items}"
                                           var="idGimnasioItem"
                                           itemValue="#{idGimnasioItem}"
                                           itemLabel="#{idGimnasioItem.razonSocial}"
                                           />
                        </p:selectOneMenu>

                        <p:outputLabel value="#{myBundle.CreateUsuariosLabel_nivel}" for="nivel" />
                        <p:selectOneMenu id="nivel" value="#{usuariosController.selected.nivel}" required="true">
                            <f:selectItem itemLabel="Seleccione Uno" itemValue="" />
                            <f:selectItem itemLabel="Administrador" itemValue="1" />
                            <f:selectItem itemLabel="Propietario" itemValue="2" />
                            <f:selectItem itemLabel="Encargado" itemValue="3" />                            
                        </p:selectOneMenu>

                    
                    </p:panelGrid>
                    <p:commandButton actionListener="#{usuariosController.save}" value="#{myBundle.Save}" update="display,:UsuariosListForm:datalist,:growl" oncomplete="handleSubmit(xhr,status,args,PF('UsuariosEditDialog'));">
                        <p:confirm header="#{myBundle.ConfirmationHeader}" message="#{myBundle.ConfirmEditMessage}" icon="ui-icon-alert"/>
                    </p:commandButton>
                    <p:commandButton value="#{myBundle.Cancel}" oncomplete="PF('UsuariosEditDialog').hide()" update="display" process="@this" immediate="true" resetValues="true"/>
                </h:panelGroup>

            </h:form>

        </p:dialog>

    </ui:composition>

</html>

src/main/webapp/app/usuarios/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="UsuariosViewDlg" widgetVar="UsuariosViewDialog" styleClass="modalResponsivo" modal="true" resizable="false"  appendTo="@(body)" header="#{myBundle.ViewUsuariosTitle}" closeOnEscape="true">

            <h:form id="UsuariosViewForm">

                <h:panelGroup id="display">
                    <p:panelGrid columns="2" columnClasses="column,sui-g-12 ui-md-2,ui-g-12 ui-md-10" rendered="#{usuariosController.selected != null}">

                        <h:outputText value="#{myBundle.ViewUsuariosLabel_idUsuario}"/>
                        <h:outputText value="#{usuariosController.selected.idUsuario}" title="#{myBundle.ViewUsuariosTitle_idUsuario}"/>

                        <h:outputText value="#{myBundle.ViewUsuariosLabel_nombreUsuario}"/>
                        <h:outputText value="#{usuariosController.selected.nombreUsuario}" title="#{myBundle.ViewUsuariosTitle_nombreUsuario}"/>

                        <h:outputText value="#{myBundle.ViewUsuariosLabel_nombre}"/>
                        <h:outputText value="#{usuariosController.selected.nombre}" title="#{myBundle.ViewUsuariosTitle_nombre}"/>

                        <h:outputText value="Gimnasio"/>
                        <h:outputText value="#{usuariosController.selected.idGimnasio.razonSocial}" title="Gimnasio"/>

                        <h:outputText value="#{myBundle.ViewUsuariosLabel_estado}"/>
                        <h:outputText value="#{usuariosController.evalEstado(usuariosController.selected.estado)}" title="#{myBundle.ViewUsuariosTitle_estado}"/>

                        <h:outputText value="#{myBundle.ViewUsuariosLabel_fechaAcceso}"/>
                        <h:outputText value="#{usuariosController.selected.fechaAcceso}" title="#{myBundle.ViewUsuariosTitle_fechaAcceso}">
                            <f:convertDateTime pattern="dd/MM/yyyy HH:mm:ss" />
                        </h:outputText>
                        
                        <h:outputText value="#{myBundle.ViewUsuariosLabel_nivel}"/>
                        <h:outputText value="#{usuariosController.evalNivel(usuariosController.selected.nivel)}" title="#{myBundle.ViewUsuariosTitle_nivel}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{myBundle.Close}" oncomplete="PF('UsuariosViewDialog').hide()" update="display" process="@this" immediate="true" resetValues="true"/>                </h:panelGroup>

            </h:form>

        </p:dialog>

    </ui:composition>

</html>

src/main/webapp/app/usuarios/changePass.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/app/template.xhtml">
        <ui:define name="body">
            <h:form id="UsuariosChangeForm">

                <p:panel id="display" header="Cambiar Contraseña">
                    <p:fieldset>
                    <p:panelGrid  columns="2" columnClasses="column">

                        <h:outputLabel value="Clave Actual" for="oldPass" />
                        <p:password id="oldPass" value="#{usuariosController.oldPass}" title="#{myBundle.EditUsuariosPassActual}" required="true" requiredMessage="Favor ingrese su contraseña Actual"/>

                        <p:outputLabel value="Nueva Clave" for="newPass1" />
                        <p:password id="newPass1" value="#{usuariosController.newPass1}" title="#{myBundle.EditUsuariosNewPass1}" required="true" requiredMessage="Favor ingrese su nueva contraseña"/>

                        <p:outputLabel value="Repita Clave" for="newPass2" />
                        <p:password id="newPass2" value="#{usuariosController.newPass2}" title="#{myBundle.EditUsuariosNewPass1}" required="true" requiredMessage="Favor ingrese de nuevo su contraseña nueva"/>

                    </p:panelGrid>
                    </p:fieldset>
                    <p:commandButton actionListener="#{usuariosController.updatePass}" value="#{myBundle.Save}" 
                                     update=":growl" oncomplete="myFunction()"/>
          
                </p:panel>

            </h:form>

        </ui:define>

    </ui:composition>
</html>